#include <LanguageISOCodes.h>

using namespace std;

map<string, string> LanguageISOCodes::getLanguageList()
{
    return _lang_map;
};

// Return the name for the input language code
string LanguageISOCodes::getLanguageName(string code)
{
    if(_lang_map.find(code) != _lang_map.end())
        return _lang_map[code];
    else
        return "Unknown";
};

// Return the code for the input language name or "None" if it's not been found
string LanguageISOCodes::getLanguageCode(string name)
{
    for (auto &i : _lang_map)
    {
        if (i.second == name) { return i.first; };
    }
    return "None";
};

map<string,string> LanguageISOCodes::_lang_map {
        {"af", "Afrikaans"},
        {"sq", "Albanian"},
        {"am", "Amharic"},
        {"ar", "Arabic"},
        {"hy", "Armenian"},
        {"az", "Azerbaijani"},
        {"bjs", "Bajan"},
        {"rm", "Balkan Gipsy"},
        {"eu", "Basque"},
        {"be", "Belarusian"},
        {"bn", "Bengali"},
        {"bem", "Bemba"},
        {"bi", "Bislama"},
        {"bs", "Bosnian"},
        {"br", "Breton"},
        {"bg", "Bulgarian"},
        {"ca", "Catalan"},
        {"cop", "Coptic"},
        {"aig", "Creole English (Antigua and Barbuda)"},
        {"bah", "Creole English (Bahamas)"},
        {"gcl", "Creole English (Grenadian)"},
        {"gyn", "Creole English (Guyanese)"},
        {"jam", "Creole English (Jamaican)"},
        {"svc", "Creole English (Vincentian)"},
        {"vic", "Creole English (Virgin Islands)"},
        {"ht", "Creole French (Haitian)"},
        {"acf", "Creole French (Saint Lucian)"},
        {"crs", "Creole French (Seselwa)"},
        {"pov", "Creole Portuguese (Upper Guinea)"},
        {"ceb", "Cebuano"},
        {"cb", "Cebuano"},
        {"cha", "Chamorro"},
        {"zh", "Chinese"},
        {"zh-CN", "Chinese (Simplified)"},
        {"zh-TW", "Chinese (Traditional)"},
        {"zdj", "Comorian (Ngazidja)"},
        {"co", "Corsican"},
        {"hr", "Croatian"},
        {"cs", "Czech"},
        {"da", "Danish"},
        {"nl", "Dutch"},
        {"dzo", "Dzongkha"},
        {"en", "English"},
        {"eo", "Esperanto"},
        {"et", "Estonian"},
        {"fn", "Fanagalo"},
        {"fo", "Faroese"},
        {"fi", "Finnish"},
        {"fr", "French"},
        {"fy", "Frisian"},
        {"gl", "Galician"},
        {"ka", "Georgian"},
        {"de", "German"},
        {"el", "Greek"},
        {"grc", "Greek (Classical)"},
        {"gu", "Gujarati"},
        {"ht", "Haitian"},
        {"ha", "Hausa"},
        {"haw", "Hawaiian"},
        {"he", "Hebrew"},
        {"iw", "Hebrew"},
        {"hi", "Hindi"},
        {"hmn", "Hmong"},
        {"hu", "Hungarian"},
        {"is", "Icelandic"},
        {"ig", "Igbo"},
        {"id", "Indonesian"},
        {"kal", "Inuktitut (Greenlandic)"},
        {"ga", "Irish"},
        {"it", "Italian"},
        {"ja", "Japanese"},
        {"jv", "Javanese"},
        {"jw", "Javanese"},
        {"kn", "Kannada"},
        {"kk", "Kazakh"},
        {"kea", "Kabuverdianu"},
        {"kab", "Kabylian"},
        {"km", "Khmer"},
        {"rw", "Kinyarwanda"},
        {"run", "Kirundi"},
        {"ko", "Korean"},
        {"ku", "Kurdish"},
        {"ky", "Kyrgyz"},
        {"lo", "Lao"},
        {"la", "Latin"},
        {"lv", "Latvian"},
        {"lt", "Lithuanian"},
        {"lb", "Luxembourgish"},
        {"mk", "Macedonian"},
        {"mg", "Malagasy"},
        {"ms", "Malay"},
        {"ml", "Malayalam"},
        {"div", "Maldivian"},
        {"mt", "Maltese"},
        {"gv", "Manx Gaelic"},
        {"mi", "Maori"},
        {"mr", "Marathi"},
        {"mh", "Marshallese"},
        {"men", "Mende"},
        {"mn", "Mongolian"},
        {"mfe", "Morisyen"},
        {"my", "Myanmar (Burmese)"},
        {"ne", "Nepali"},
        {"niu", "Niuean"},
        {"no", "Norwegian"},
        {"ny", "Nyanja (Chichewa)"},
        {"or", "Odia (Oriya)"},
        {"pau", "Palauan"},
        {"pap", "Papiamentu"},
        {"ps", "Pashto"},
        {"fa", "Persian"},
        {"pis", "Pijin"},
        {"pl", "Polish"},
        {"pt", "Portuguese"},
        {"pot", "Potawatomi"},
        {"pa", "Punjabi"},
        {"qu", "Quechua"},
        {"ro", "Romanian"},
        {"ru", "Russian"},
        {"sm", "Samoan"},
        {"smo", "Samoan"},
        {"sg", "Sango"},
        {"gd", "Scots (Gaelic)"},
        {"sr", "Serbian"},
        {"st", "Sesotho"},
        {"sn", "Shona"},
        {"sna", "Shona"},
        {"sd", "Sindhi"},
        {"si", "Sinhala (Sinhalese)"},
        {"sk", "Slovak"},
        {"sl", "Slovenian"},
        {"so", "Somali"},
        {"nso", "Sotho, Southern"},
        {"es", "Spanish"},
        {"srn", "Sranan Tongo"},
        {"su", "Sundanese"},
        {"sw", "Swahili"},
        {"sv", "Swedish"},
        {"syc", "Syriac (Aramaic)"},
        {"tl", "Tagalog (Filipino)"},
        {"tg", "Tajik"},
        {"tmh", "Tamashek (Tuareg)"},
        {"ta", "Tamil"},
        {"tt", "Tatar"},
        {"te", "Telugu"},
        {"tet", "Tetum"},
        {"th", "Thai"},
        {"bod", "Tibetan"},
        {"ti", "Tigrinya"},
        {"ton", "Tongan"},
        {"tpi", "Tok Pisin"},
        {"tkl", "Tokelauan"},
        {"tn", "Tswana"},
        {"tr", "Turkish"},
        {"tk", "Turkmen"},
        {"tvl", "Tuvaluan"},
        {"uk", "Ukrainian"},
        {"ppk", "Uma"},
        {"ur", "Urdu"},
        {"ug", "Uyghur"},
        {"uz", "Uzbek"},
        {"vi", "Vietnamese"},
        {"wls", "Wallisian"},
        {"cy", "Welsh"},
        {"wo", "Wolof"},
        {"xh", "Xhosa"},
        {"yi", "Yiddish"},
        {"yo", "Yoruba"},
        {"zu", "Zulu"}
    };
